# Generated by Django 3.1.3 on 2020-11-23 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('given_name', models.CharField(max_length=100)),
                ('family_name', models.CharField(max_length=100)),
                ('picture', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=30)),
                ('verified_email', models.BooleanField(default=False)),
                ('locale', models.CharField(max_length=4)),
            ],
        ),
    ]
